- hosts: k8s-workers
  tasks:
    - name: "Install web server"
      package:
        name: httpd
        state: present
    - name: "Copy Files"
      copy:
        src: "./index.html"
        dest: "/var/www/html"
    - name: "Start the Server"
      service:
        name: httpd
        state: started
